### ISSUE TITLE
is useDaysActions deprecated?

### ISSUE THREAD

**Issue by cheolhow** [rehookify/datepicker#16]
https://github.com/rehookify/datepicker/tree/v3.2.0#usedaysactions

setDay in useDaysActions seems necessary when controlling the component from outside.

**Comment by Feshchenko** [comment]
Hi, @cheolhow, thanks for reaching me with this question
`setDay` was deleted in v4.0 since the date picker is controlled now.
In v4.0 you need to pass `selectedDates` and `onDateChange` to the config (like in README examples)[https://github.com/rehookify/datepicker#with-hook]
So you can control it outside wo this action.

**Comment by cheolhow** [comment]
@Feshchenko Thank you for answer. As in your answer, setDay doesn't seem necessary.
